### ISSUE TITLE
CT tsc failed with code:2

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#106]
```
number-play : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Fatal error: tsc failed with code: 2
stdout:
js/game/model/CountingGameLevel.ts(28,69): error TS2749: 'PlayObjectType' refers to a value, but is being used as a type here. Did you mean 'typeof PlayObjectType'?
js/game/model/CountingGameLevel.ts(29,61): error TS2749: 'PlayObjectType' refers to a value, but is being used as a type here. Did you mean 'typeof PlayObjectType'?
js/game/model/CountingGameLevel.ts(48,65): error TS2345: Argument of type 'Enumeration' is not assignable to parameter of type 'RichEnumerationContainer<PlayObjectType>'.
Property 'enumeration' is missing in type 'Enumeration' but required in type 'RichEnumerationContainer<PlayObjectType>'.
js/game/model/CountingGameLevel.ts(60,45): error TS2749: 'PlayObjectType' refers to a value, but is being used as a type here. Did you mean 'typeof PlayObjectType'?
js/game/model/CountingGameLevel.ts(61,45): error TS2339: Property 'enumeration' does not exist on type 'Enumeration'.
js/game/view/CountingGameLevelNode.ts(76,67): error TS2345: Argument of type 'Enumeration' is not assignable to parameter of type 'RichEnumerationContainer<any>'.
Property 'enumeration' is missing in type 'Enumeration' but required in type 'RichEnumerationContainer<any>'.
js/game/view/CountingGameLevelNode.ts(76,108): error TS2339: Property 'GROUPING' does not exist on type 'Enumeration'.
js/game/view/CountingGameLevelNode.ts(77,67): error TS2345: Argument of type 'Enumeration' is not assignable to parameter of type 'RichEnumerationContainer<any>'.
js/game/view/CountingGameLevelNode.ts(77,108): error TS2339: Property 'NO_GROUPING' does not exist on type 'Enumeration'.
js/common/model/NumberPlayModel.ts(23,72): error TS2749: 'GroupingLinkingType' refers to a value, but is being used as a type here. Did you mean 'typeof GroupingLinkingType'?
js/common/model/NumberPlayModel.ts(39,69): error TS2345: Argument of type 'Enumeration' is not assignable to parameter of type 'RichEnumerationContainer<any>'.
js/common/model/NumberPlayModel.ts(39,110): error TS2339: Property 'NO_GROUPING' does not exist on type 'Enumeration'.

14 problems found.

stderr:

Snapshot from 1/4/2022, 8:26:26 AM

----------------------------------

number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1641309986348%22%2C%22timestamp%22%3A1641311877756%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'values')
TypeError: Cannot read properties of undefined (reading 'values')
at new RichEnumerationProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/axon/js/RichEnumerationProperty.js:22:53)
at new NumberPlayModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/number-play/js/common/model/NumberPlayModel.js:26:40)
at TenScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/number-play/js/ten/TenScreen.js:64:17)
at TenScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/joist/js/Screen.js:205:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/joist/js/Sim.js:657:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/joist/js/Sim.js:667:21
id: Bayes Chrome
Snapshot from 1/4/2022, 8:26:26 AM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1641309986348%22%2C%22timestamp%22%3A1641313239597%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'values')
TypeError: Cannot read properties of undefined (reading 'values')
at new RichEnumerationProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/axon/js/RichEnumerationProperty.js:22:53)
at new NumberPlayModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/number-play/js/common/model/NumberPlayModel.js:26:40)
at TenScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/number-play/js/ten/TenScreen.js:64:17)
at TenScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/joist/js/Screen.js:205:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/joist/js/Sim.js:657:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1641309986348/chipper/dist/js/joist/js/Sim.js:667:21
id: Bayes Chrome
Snapshot from 1/4/2022, 8:26:26 AM
```

**Comment by chrisklus** [comment]
thanks @KatieWoe! I think I forgot to push changes to `counting-common` along with a push to Number Play. Fixed now, closing.
