### ISSUE TITLE
CT did not find matching Node

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#12]
```
number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612792222363%22%2C%22timestamp%22%3A1612793537285%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Uncaught Error: Assertion failed: Did not find matching Node
Error: Assertion failed: Did not find matching Node
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/assert/js/assert.js:25:13)
at OnesPlayAreaNode.findPaperNumberNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/number-play/js/common/view/OnesPlayAreaNode.js:193:15)
at OnesPlayAreaNode.tryToCombineNumbers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/number-play/js/common/view/OnesPlayAreaNode.js:204:30)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/number-play/js/common/view/PaperNumberNode.js:87:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/scenery/js/listeners/DragListener.js:338:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/scenery/js/listeners/PressListener.js:646:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/axon/js/Action.js:225:18)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/scenery/js/listeners/PressListener.js:427:25)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/scenery/js/listeners/DragListener.js:334:11)
at DragListener.pointerUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612792222363/scenery/js/listeners/PressListener.js:757:12)
id: Bayes Chrome
Snapshot from 2/8/2021, 6:50:22 AM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! I'm not sure what this was from but it is very stale now and I haven't seen it on CT, closing.
