### ISSUE TITLE
CT property value not valid

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#142]
```
number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643950572061%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/ValidatorDef.js:294:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/validate.js:33:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:122:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:228:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:159:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:106:50
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Emitter.js:37:24
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643960756202%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/ValidatorDef.js:294:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/validate.js:33:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:122:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:228:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:159:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:106:50
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Emitter.js:37:24
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

number-play : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643959312246%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/ValidatorDef.js:294:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/validate.js:33:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:122:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:228:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:159:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:106:50
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Emitter.js:37:24
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

number-play : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643991878339%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/ValidatorDef.js:294:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/validate.js:33:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:122:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:228:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:159:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:106:50
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Emitter.js:37:24
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643950014291%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/ValidatorDef.js:294:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/validate.js:33:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:122:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:228:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:159:14)
at EnumerationProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:298:10)
at Subitizer.setRandomPlayObjectType (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/number-play/js/game/model/Subitizer.js:275:36)
at Subitizer.newChallenge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/number-play/js/game/model/Subitizer.js:200:10)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643961604127%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/ValidatorDef.js:294:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/validate.js:33:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:122:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:228:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:159:14)
at EnumerationProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:298:10)
at Subitizer.setRandomPlayObjectType (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/number-play/js/game/model/Subitizer.js:275:36)
at Subitizer.newChallenge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/number-play/js/game/model/Subitizer.js:200:10)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643950574524%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/ValidatorDef.js:294:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/validate.js:33:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:122:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:228:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:159:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:106:50
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Emitter.js:37:24
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643965324547%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/ValidatorDef.js:294:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/validate.js:33:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:122:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:228:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:159:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:106:50
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Emitter.js:37:24
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

number-play : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643957358123%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/ValidatorDef.js:294:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/validate.js:33:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:122:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:228:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:159:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/sun/js/buttons/RectangularRadioButton.js:106:50
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Emitter.js:37:24
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM

----------------------------------

number-play : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1643947237933%22%2C%22timestamp%22%3A1643966823018%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
Error: Assertion failed: Property value not valid: value not in validValues: PAPER_NUMBER
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/ValidatorDef.js:294:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/validate.js:33:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:122:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:228:23)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:159:14)
at EnumerationProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/axon/js/Property.js:298:10)
at Subitizer.setRandomPlayObjectType (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/number-play/js/game/model/Subitizer.js:275:36)
at Subitizer.newChallenge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643947237933/chipper/dist/js/number-play/js/game/model/Subitizer.js:200:10)
id: Bayes Chrome
Snapshot from 2/3/2022, 9:00:37 PM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! This was fixed by work in https://github.com/phetsims/counting-common/issues/7, and I haven't seen the error on CT since then. Closing.
