### ISSUE TITLE
CT Assertion failed: value failed isValidValue: 11

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#154]
```
number-play : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1647570878576%22%2C%22timestamp%22%3A1647593747570%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: 11
Error: Assertion failed: value failed isValidValue: 11
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/axon/js/ValidatorDef.js:299:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/axon/js/validate.js:33:18)
at NumberProperty.validateNumberAndRangeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/axon/js/NumberProperty.js:112:9)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/axon/js/NumberProperty.js:255:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/axon/js/NumberProperty.js:144:68
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/axon/js/Property.js:227:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/axon/js/Property.js:156:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647570878576/chipper/dist/js/axon/js/Property.js:297:10)
id: Bayes Chrome
Snapshot from 3/17/2022, 8:34:38 PM
```

**Comment by chrisklus** [comment]
There are newer CT issues related to this, closing.
