### ISSUE TITLE
CT assertion failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#16]
```
number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620280021078%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620289194929%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620305164251%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620287588791%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620301565208%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620281104025%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620289270263%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620303548752%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620280625170%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620292744158%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620306065373%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620294988736%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

number-play : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620306126056%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at PlayObjectGroup.sendPlayObjectToSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObjectGroup.js:106:17)
at PlayObject.sendToGroupSpot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/model/PlayObject.js:72:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/ObjectsPlayAreaNode.js:82:26
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/TinyEmitter.js:86:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:269:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/axon/js/Property.js:184:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/number-play/js/common/view/PlayObjectNode.js:71:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/scenery/js/listeners/PressListener.js:680:17)
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! This looks related to grouping code that no longer exists since we started using paper ones for objects, closing.
