### ISSUE TITLE
CT reentry detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#176]
```
number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654297698413%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=1, oldValue=2
Error: Assertion failed: reentry detected, value=1, oldValue=2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (AbstractProperty.ts:252:14)
at _notifyListeners (AbstractProperty.ts:206:13)
at set (Property.ts:67:10)
at set (Property.ts:53:9)
at (OnesPlayArea.ts:367:4)
at listener (TinyEmitter.ts:94:8)
at emit (AbstractProperty.ts:255:22)
at _notifyListeners (AbstractProperty.ts:206:13)
at set (Property.ts:67:10)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! This is being worked on in https://github.com/phetsims/number-play/issues/174.

**Comment by chrisklus** [comment]
This was fixed in https://github.com/phetsims/number-play/issues/174 and is no longer coming up on CT, closing.
