### ISSUE TITLE
CT A play area should not need to create more than one counting objectat a time

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#178]
```
number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1658156886162%22%2C%22timestamp%22%3A1658161680603%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: A play area should not need to create more than one counting objectat a time to match the opposite play area: 2
Error: Assertion failed: A play area should not need to create more than one counting objectat a time to match the opposite play area: 2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658156886162/assert/js/assert.js:28:13)
at assert (NumberPlayModel.ts:102:16)
at matchPlayAreaToNewValue (NumberPlayModel.ts:79:17)
at derivation (DerivedProperty.ts:38:9)
at getDerivedValue (DerivedProperty.ts:151:17)
at listener (TinyEmitter.ts:93:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
at set (Property.ts:68:10)
at set (Property.ts:54:9)
id: Bayes Puppeteer
Snapshot from 7/18/2022, 9:08:06 AM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! This is being worked on in https://github.com/phetsims/number-play/issues/174.

**Comment by chrisklus** [comment]
This was fixed in https://github.com/phetsims/number-play/issues/174 and is no longer coming up on CT, closing.
