### ISSUE TITLE
CT paperNumbers should exist in play area

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#183]
```
number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659374015149/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659374015149%22%2C%22timestamp%22%3A1659379717775%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: paperNumbers should exist in play area
Error: Assertion failed: paperNumbers should exist in play area
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659374015149/assert/js/assert.js:28:13)
at assert (OnesPlayArea.ts:204:14)
at returnPaperNumberToBucket (NumberPlayModel.ts:109:17)
at baseTimes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659374015149/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659374015149/sherpa/lib/lodash-4.17.4.js:16095:20)
at times (NumberPlayModel.ts:108:8)
at matchPlayAreaToNewValue (NumberPlayModel.ts:89:13)
at listener (TinyEmitter.ts:94:8)
at emit (ReadOnlyProperty.ts:261:22)
at _notifyListeners (ReadOnlyProperty.ts:212:13)
id: Bayes Puppeteer
Snapshot from 8/1/2022, 11:13:35 AM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659374015149/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1659374015149%22%2C%22timestamp%22%3A1659379570153%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: paperNumber already removed from sum
Error: Assertion failed: paperNumber already removed from sum
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659374015149/assert/js/assert.js:28:13)
at assert (OnesPlayAreaNode.ts:404:16)
at onNumberDragFinished (OnesPlayAreaNode.ts:86:11)
at listener (TinyEmitter.ts:94:8)
at emit (Emitter.ts:60:21)
at emit (PaperNumberNode.ts:135:30)
at _end (DragListener.ts:394:24)
at callback (PressListener.ts:752:16)
at apply (PhetioAction.ts:124:16)
at execute (PressListener.ts:510:24)
id: Bayes Puppeteer
Snapshot from 8/1/2022, 11:13:35 AM
```

**Comment by KatieWoe** [comment]
May be related:
```
number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667836584432/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667836584432%22%2C%22timestamp%22%3A1667838418845%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: countingObjects should exist in play area
Error: Assertion failed: countingObjects should exist in play area
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667836584432/assert/js/assert.js:28:13)
at assert (CountingPlayArea.ts:212:14)
at returnCountingObjectToBucket (NumberPlayModel.ts:109:17)
at baseTimes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667836584432/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667836584432/sherpa/lib/lodash-4.17.4.js:16095:20)
at times (NumberPlayModel.ts:108:8)
at matchPlayAreaToNewValue (NumberPlayModel.ts:89:13)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 8:56:24 AM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667836584432/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667836584432%22%2C%22timestamp%22%3A1667838475262%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: countingObject already removed from sum
Error: Assertion failed: countingObject already removed from sum
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667836584432/assert/js/assert.js:28:13)
at assert (CountingPlayAreaNode.ts:456:16)
at onNumberDragFinished (CountingPlayAreaNode.ts:90:11)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (CountingObjectNode.ts:134:30)
at _end (DragListener.ts:394:24)
at callback (PressListener.ts:752:16)
at apply (PhetioAction.ts:124:16)
at execute (PressListener.ts:510:24)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 8:56:24 AM

----------------------------------

number-play : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667836584432/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1667836584432%22%2C%22timestamp%22%3A1667840157719%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: countingObjects should exist in play area
Error: Assertion failed: countingObjects should exist in play area
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667836584432/assert/js/assert.js:28:13)
at assert (CountingPlayArea.ts:212:14)
at returnCountingObjectToBucket (NumberPlayModel.ts:109:17)
at baseTimes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667836584432/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667836584432/sherpa/lib/lodash-4.17.4.js:16095:20)
at times (NumberPlayModel.ts:108:8)
at matchPlayAreaToNewValue (NumberPlayModel.ts:89:13)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 8:56:24 AM
```
