### ISSUE TITLE
CT Cannot read properties of undefined (reading 'moveToFront')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#186]
```
number-play : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201217522%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'moveToFront')
TypeError: Cannot read properties of undefined (reading 'moveToFront')
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201217522%7D&fuzz&memoryLimit=1000:975:2189338)
at Proxy.forEach
at i.start [as _start] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201217522%7D&fuzz&memoryLimit=1000:975:2189291)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201217522%7D&fuzz&memoryLimit=1000:975:807450)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201217522%7D&fuzz&memoryLimit=1000:975:800206)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201217522%7D&fuzz&memoryLimit=1000:975:1183365)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201217522%7D&fuzz&memoryLimit=1000:975:797572)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201217522%7D&fuzz&memoryLimit=1000:975:807141)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201217522%7D&fuzz&memoryLimit=1000:975:2189650)
at Object.down (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201217522%7D&fuzz&memoryLimit=1000:975:812109)
id: Bayes Puppeteer
Snapshot from 9/26/2022, 5:00:52 AM

----------------------------------

number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664197479064%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: countingObjectType not found!
Error: Assertion failed: countingObjectType not found!
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/assert/js/assert.js:28:13)
at assert (LabScreenView.ts:296:14)
at getCountingObjectType (LabScreenView.ts:374:36)
at getCorrespondingPlayAreaNode (LabScreenView.ts:340:36)
at getCountingObjectNode (DraggableTenFrameNode.ts:57:45)
at Proxy.forEach
at forEach (DraggableTenFrameNode.ts:56:33)
at _start (DragListener.ts:365:26)
at callback (PressListener.ts:729:16)
at apply (PhetioAction.ts:124:16)
id: Bayes Puppeteer
Snapshot from 9/26/2022, 5:00:52 AM

----------------------------------

number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664202641269%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: A play area should not need to create more than one counting objectat a time to match the opposite play area: 4
Error: Assertion failed: A play area should not need to create more than one counting objectat a time to match the opposite play area: 4
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/assert/js/assert.js:28:13)
at assert (NumberPlayModel.ts:100:16)
at matchPlayAreaToNewValue (NumberPlayModel.ts:76:13)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (CountingCommonModel.ts:152:4)
at calculateTotal (OnesPlayAreaNode.ts:185:18)
id: Bayes Puppeteer
Snapshot from 9/26/2022, 5:00:52 AM

----------------------------------

number-play : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664201305099%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: attempted to push away countingObject that was not over ten frame
Error: Assertion failed: attempted to push away countingObject that was not over ten frame
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/assert/js/assert.js:28:13)
at assert (TenFrame.ts:73:14)
at pushAwayCountingObject (OnesPlayAreaNode.ts:334:28)
at Array.forEach
at forEach (OnesPlayAreaNode.ts:318:37)
at tryToAddToTenFrame (OnesPlayAreaNode.ts:251:14)
at tryToCombineNumbers (PaperNumberNode.ts:133:10)
at _end (DragListener.ts:394:24)
at callback (PressListener.ts:752:16)
at apply (PhetioAction.ts:124:16)
id: Bayes Puppeteer
Snapshot from 9/26/2022, 5:00:52 AM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664196589456%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/assert/js/assert.js:28:13)
at assert (Node.ts:906:14)
at removeChild (InequalitySymbolsCreatorPanel.ts:70:38)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (Animation.js:320:25)
at listener (TinyEmitter.ts:95:8)
at emit (Sim.ts:428:16)
at apply (PhetioAction.ts:124:16)
at execute (Sim.ts:1019:30)
id: Bayes Puppeteer
Snapshot from 9/26/2022, 5:00:52 AM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664202717879%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:393:37)
at remove (LabScreenView.ts:332:35)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (Animation.js:320:25)
at listener (TinyEmitter.ts:95:8)
at emit (Sim.ts:428:16)
at apply (PhetioAction.ts:124:16)
id: Bayes Puppeteer
Snapshot from 9/26/2022, 5:00:52 AM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1664190052273%22%2C%22timestamp%22%3A1664197354479%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: attempted to push away countingObject that was not over ten frame
Error: Assertion failed: attempted to push away countingObject that was not over ten frame
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664190052273/assert/js/assert.js:28:13)
at assert (TenFrame.ts:73:14)
at pushAwayCountingObject (OnesPlayAreaNode.ts:334:28)
at Array.forEach
at forEach (OnesPlayAreaNode.ts:318:37)
at tryToAddToTenFrame (OnesPlayAreaNode.ts:251:14)
at tryToCombineNumbers (PaperNumberNode.ts:133:10)
at _end (DragListener.ts:394:24)
at callback (PressListener.ts:752:16)
at apply (PhetioAction.ts:124:16)
id: Bayes Puppeteer
Snapshot from 9/26/2022, 5:00:52 AM
```

**Comment by chrisklus** [comment]
I fixed this issue in the above commit and haven't seen it on CT since. I opened #187 to track down a different assertion in this stack and I think the rest already have issues or will be fixed by the work in #187. Closing.
