### ISSUE TITLE
CT Assertion failed: countingObjectType not found!

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#187]
Making a side issue from https://github.com/phetsims/number-play/issues/186 since there were multiple problems in that stack.

**Comment by chrisklus** [comment]
In #33 I added logic to grab counting objects not in ten frames before any objects are removed from ten frames (regardless of how far away things are) when the down arrow is clicked to return a counting object. For this issue I need to properly remove counting objects from ten frames when they are selected to be returned.

**Comment by chrisklus** [comment]
Fixed in the above commit, closing.

**Comment by pixelzoom** [comment]
Reopening. This occurred in CT last night:

```
number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1672892325918/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1672892325918%22%2C%22timestamp%22%3A1672896955054%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: countingObjectType not found!
Error: Assertion failed: countingObjectType not found!
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1672892325918/assert/js/assert.js:28:13)
at assert (LabScreenView.ts:292:14)
at getCountingObjectType (LabScreenView.ts:377:36)
at getCorrespondingPlayAreaNode (LabScreenView.ts:343:36)
at getCountingObjectNode (DraggableTenFrameNode.ts:57:45)
at Proxy.forEach
at forEach (DraggableTenFrameNode.ts:56:33)
at _start (DragListener.ts:365:26)
at callback (PressListener.ts:727:16)
at apply (PhetioAction.ts:157:16)
id: Bayes Puppeteer
Snapshot from 1/4/2023, 9:18:45 PM
```

**Comment by pixelzoom** [comment]
Migrating to number-suite-common, since this involves LabScreenView.
