### ISSUE TITLE
CT Cannot read properties of undefined (reading 'labStringProperty')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#191]
```
number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671785232041%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-play-main.ts:65:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671791824268%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-play-main.ts:65:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-play : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671791024069%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-play-main.ts:65:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671784728996%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-play-main.ts:65:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671792000354%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-play-main.ts:65:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671786208274%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-play-main.ts:65:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671793190728%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-play-main.ts:65:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-play : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671786196882%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-play-main.ts:65:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM

----------------------------------

number-play : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671782940478/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1671782940478%22%2C%22timestamp%22%3A1671792694571%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'labStringProperty')
TypeError: Cannot read properties of undefined (reading 'labStringProperty')
at labStringProperty (LabScreen.ts:27:44)
at (number-play-main.ts:65:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 1:09:00 AM
```

**Comment by pixelzoom** [comment]
Duplicate of https://github.com/phetsims/number-compare/issues/8. I verified that it's no longer an issue. Closing.
