### ISSUE TITLE
CT matching tenFrameNode not found!

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#195]
```
number-compare : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669628102736/number-compare/number-compare_en.html?continuousTest=%7B%22test%22%3A%5B%22number-compare%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1669628102736%22%2C%22timestamp%22%3A1669637012626%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: matching tenFrameNode not found!
Error: Assertion failed: matching tenFrameNode not found!
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669628102736/assert/js/assert.js:28:13)
at assert (LabScreenView.ts:360:14)
at getTenFrameNode (LabScreenView.ts:303:36)
at dropListener (DraggableTenFrameNode.ts:68:16)
at _end (DragListener.ts:394:24)
at callback (PressListener.ts:752:16)
at apply (PhetioAction.ts:157:16)
at execute (PressListener.ts:510:24)
at release (DragListener.ts:390:10)
at release (PressListener.ts:851:11)
id: Bayes Puppeteer
Snapshot from 11/28/2022, 2:35:02 AM
```

**Comment by pixelzoom** [comment]
Reproduced in master with this URL for the "multitouch-fuzz : unbuilt" CT test:
http://localhost:8080/number-play/number-play_en.html?brand=phet&screens=4&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false

Note that I added `screens=4` to the URL, so that I'm running only the Lab screen. This makes the error occur more quickly.

**Comment by pixelzoom** [comment]
I tried to shorten the URL, and could not reproduce with:
http://localhost:8080/number-play/number-play_en.html?brand=phet&screens=4&ea&fuzz

So `fuzzPointer=2` is required to reproduce, and this is therefore likely specific to multitouch.

`supportsPanAndZoom` is not required to reproduce, since it fails in CT with values of `true` and `false`.  But using `supportsPanAndZoom=false` makes it occur more quickly, probably because the sim isn't spending time panning and zooming.

So... The URL for testing is:
 
* http://localhost:8080/number-play/number-play_en.html?brand=phet&screens=4&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false

**Comment by pixelzoom** [comment]
Here's a current stack trace when running from master unbuilt:

> assert.js:28 Uncaught Error: Assertion failed: matching tenFrameNode not found!
    at window.assertions.assertFunction (assert.js:28:13)
    at LabScreenView.getTenFrameNode (LabScreenView.ts:360:15)
    at Object.dropListener (LabScreenView.ts:303:37)
    at DragListener.end [as _end] (DraggableTenFrameNode.ts:68:17)
    at DragListener.ts:394:25
    at DragListener.onRelease (PressListener.ts:750:17)
    at PhetioAction.execute (PhetioAction.ts:157:17)
    at DragListener.release (PressListener.ts:508:25)
    at DragListener.release (DragListener.ts:390:11)
    at DragListener.pointerUp (PressListener.ts:849:12)
