### ISSUE TITLE
Bad maxWidth for LocaleSwitch labels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#210]
Probably related to changes made in https://github.com/phetsims/number-compare/issues/18....

I'm seeing bad maxWidth for the LocaleSwitch labels in master, see below.  I'll investigate.

<img width="337" alt="screenshot_2287" src="https://user-images.githubusercontent.com/3046552/217327041-c4fc89f5-9f50-4c3d-9a90-9cfe4a55ce55.png">

**Comment by pixelzoom** [comment]
I fixed the above problem:

<img width="392" alt="screenshot_2290" src="https://user-images.githubusercontent.com/3046552/217386005-5bd4dbae-8ead-4454-b187-ec631db71ae1.png">

But noticed a new layout problem. If the primary locale is changed via Localization preferences, then LocaleSwitch is not reflowing its layout.  For example, here's what happens when the primary locale is changed to "Kurdish (Turkey)":

<img width="391" alt="screenshot_2289" src="https://user-images.githubusercontent.com/3046552/217386185-4f185762-a421-4159-a3d1-e18f6e1b951e.png">

**Comment by pixelzoom** [comment]
I tried this:

1. Stat Number Play
2. Go to Preferences >Simulation, turn on "Second Language" switch, select "English (United Kingdom)"
3. Go to Preferences > Localization, select "Norwegian Nynorsk", or any locale name that is longer than "English".

The sim will immediately fail with:

> Node.ts:2760 Uncaught RangeError: Maximum call stack size exceeded
    at Text.onTransformChange (Node.ts:2760:28)
    at TinyEmitter.emit (TinyEmitter.ts:95:9)
    at Transform3.invalidate (Transform3.js? [sm]:102:24)
    at Transform3.append (Transform3.js? [sm]:155:10)
    at Text.appendMatrix (Node.ts:2676:21)
    at Text.scale (Node.ts:2406:16)
    at Text.scale (Node.ts:2394:14)
    at Text.updateMaxDimension (Node.ts:2807:12)
    at Text.setMaxWidth (Node.ts:2852:12)
    at set maxWidth [as maxWidth] (Node.ts:2860:10)

**Comment by pixelzoom** [comment]
Fixed in the above commits. Closing.
