### ISSUE TITLE
CT emitting reentrant depth of 1000 seems like a infinite loop to me!

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#239]
```
number-play : fuzz : unbuilt : listenerOrderRandom
Tried to run 3 times, never completed, failure: Error: Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["number-play","fuzz","unbuilt","listenerOrderRandom"]
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1717326050113%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717342442235%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1717326050113%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717342442235%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717342442235%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 558837
[CONSOLE] continuous-test-load
Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["number-play","fuzz","unbuilt","listenerOrderRandom"]

id: "Sparky Node Puppeteer"
Snapshot from 6/2/2024, 5:00:50 AM

----------------------------------

number-play : fuzz : unbuilt : listenerOrderRandom
Tried to run 3 times, never completed, failure: Error: Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["number-play","fuzz","unbuilt","listenerOrderRandom"]
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1717326050113%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717375410762%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1717326050113%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717375410762%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717375410762%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 779800
[CONSOLE] continuous-test-load
Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["number-play","fuzz","unbuilt","listenerOrderRandom"]

id: "Sparky Node Puppeteer"
Snapshot from 6/2/2024, 5:00:50 AM

----------------------------------

number-play : second-language-fuzz : unbuilt : query-parameters
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1717326050113/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717327840171%7D&brand=phet&ea&fuzz&locales=*&secondLocale=es
ERROR: QUERY: brand=phet&ea&fuzz&locales=*&secondLocale=es
Error: Assertion failed: emitting reentrant depth of 1000 seems like a infinite loop to me!
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1717326050113/assert/js/assert.js:43:13
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1717326050113/assert/js/assert.js:43:13)
    at assert (TinyEmitter.ts:191:20)
    at emit (TinyStaticProperty.ts:56:9)
    at notifyListeners (Node.ts:1556:30)
    at validateBounds (Node.ts:1668:18)
    at watchedBoundsScan (Node.ts:1675:38)
    at watchedBoundsScan (Node.ts:1675:38)
    at watchedBoundsScan (Node.ts:1675:38)
    at watchedBoundsScan (Node.ts:1654:17)
    at validateWatchedBounds (Display.ts:569:19)
    at updateDisplay (Sim.ts:453:21)
    at apply (PhetioAction.ts:162:16)
    at execute (Sim.ts:1050:30)
    at stepSimulation (Sim.ts:1040:11)
    at stepOneFrame (Sim.ts:1015:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
    at requestAnimationFrame (Sim.ts:1005:11)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1717326050113%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26locales%3D*%26secondLocale%3Des&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717327840171%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1717326050113%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26locales%3D*%26secondLocale%3Des&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717327840171%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1717326050113/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717327840171%7D&brand=phet&ea&fuzz&locales=*&secondLocale=es
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed:  emitting reentrant depth of 1000 seems like a infinite loop to me!
[CONSOLE] Debug info: {
  "seed": 0.19092832962302964,
  "currentScreenName": "TwentyScreen"
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: emitting reentrant depth of 1000 seems like a infinite loop to me!
[CONSOLE] Assertion failed:  emitting reentrant depth of 1000 seems like a infinite loop to me!
[CONSOLE] Debug info: {
  "seed": 0.19092832962302964,
  "currentScreenName": "TwentyScreen"
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: emitting reentrant depth of 1000 seems like a infinite loop to me!

id: "Sparky Node Firefox"
Snapshot from 6/2/2024, 5:00:50 AM

----------------------------------

number-play : second-language-fuzz : unbuilt : query-parameters
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717374907640%7D&brand=phet&ea&fuzz&locales=*&secondLocale=es
ERROR: QUERY: brand=phet&ea&fuzz&locales=*&secondLocale=es
Uncaught Error: Assertion failed: emitting reentrant depth of 1000 seems like a infinite loop to me!
STACK: Error: Assertion failed: emitting reentrant depth of 1000 seems like a infinite loop to me!
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/assert/js/assert.js:43:13)
    at assert (TinyEmitter.ts:191:20)
    at emit (TinyStaticProperty.ts:56:9)
    at notifyListeners (Node.ts:1556:30)
    at onAccessAttempt (TinyStaticProperty.ts:31:9)
    at get (TinyStaticProperty.ts:56:20)
    at notifyListeners (Node.ts:1455:35)
    at onAccessAttempt (TinyStaticProperty.ts:31:9)
    at get (TinyStaticProperty.ts:56:20)
    at notifyListeners (Node.ts:1909:33)
    at setLocalBounds (Node.ts:1864:9)
    at  (LayoutNode.ts:46:22)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:352:22)
    at _notifyListeners (ReadOnlyProperty.ts:296:13)
    at unguardedSet (ReadOnlyProperty.ts:276:11)
    at set (Property.ts:54:10)
    at  (FlowConstraint.ts:333:35)
    at layout (LayoutConstraint.ts:201:13)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1717326050113%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26locales%3D*%26secondLocale%3Des&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717374907640%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1717326050113%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26locales%3D*%26secondLocale%3Des&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717374907640%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717374907640%7D&brand=phet&ea&fuzz&locales=*&secondLocale=es
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed:  emitting reentrant depth of 1000 seems like a infinite loop to me!
[CONSOLE] Debug info: {
  "seed": 0.23550349845340413,
  "currentScreenName": "TwentyScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: emitting reentrant depth of 1000 seems like a infinite loop to me!
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/assert/js/assert.js:43:13)
    at TinyStaticProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/TinyEmitter.js:158:21)
    at TinyStaticProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/TinyStaticProperty.js:49:10)
    at LocaleSwitch.validateBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/nodes/Node.js:1353:31)
    at TinyStaticProperty.get (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/TinyStaticProperty.js:26:10)
    at TinyStaticProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/TinyStaticProperty.js:49:20)
    at LocaleSwitch.validateBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/nodes/Node.js:1263:36)
    at TinyStaticProperty.get (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/TinyStaticProperty.js:26:10)
    at TinyStaticProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/TinyStaticProperty.js:49:20)
    at LocaleSwitch.setLocalBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/nodes/Node.js:1676:34)
    at set localBounds [as localBounds] (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/nodes/Node.js:1639:10)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/layout/nodes/LayoutNode.js:23:24
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
    at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/ReadOnlyProperty.js:264:23)
    at Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/ReadOnlyProperty.js:211:14)
    at Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/ReadOnlyProperty.js:193:12)
    at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/Property.js:48:11)
    at FlowConstraint.layout (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/layout/constraints/FlowConstraint.js:270:37)
    at FlowConstraint.updateLayout (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:188:14)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed:  emitting reentrant depth of 1000 seems like a infinite loop to me!
[CONSOLE] Debug info: {
  "seed": 0.23550349845340413,
  "currentScreenName": "TwentyScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "PopupParentNode: PreferencesDialog"
  ]
}
[PAGE ERROR] Error: Error: Assertion failed: emitting reentrant depth of 1000 seems like a infinite loop to me!
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/assert/js/assert.js:43:13)
    at TinyStaticProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/TinyEmitter.js:158:21)
    at TinyStaticProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/axon/js/TinyStaticProperty.js:49:10)
    at LocaleSwitch.validateBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/nodes/Node.js:1353:31)
    at LocaleSwitch.watchedBoundsScan (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/nodes/Node.js:1447:19)
    at TwentyScreenView.watchedBoundsScan (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/nodes/Node.js:1453:37)
    at Node.watchedBoundsScan (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/nodes/Node.js:1453:37)
    at Node.watchedBoundsScan (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/nodes/Node.js:1453:37)
    at Node.validateWatchedBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/nodes/Node.js:1433:17)
    at SimDisplay.updateDisplay (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/scenery/js/display/Display.js:359:20)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/joist/js/Sim.js:372:22
    at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/tandem/js/PhetioAction.js:137:17)
    at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/joist/js/Sim.js:885:31)
    at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/joist/js/Sim.js:875:12)
    at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/chipper/dist/js/joist/js/Sim.js:853:12)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 6/2/2024, 5:00:50 AM

----------------------------------

number-play : second-language-fuzz : unbuilt : query-parameters
Tried to run 3 times, never completed, failure: Error: Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["number-play","second-language-fuzz","unbuilt","query-parameters"]
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1717326050113%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26locales%3D*%26secondLocale%3Des&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717393976495%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1717326050113%2Fnumber-play%2Fnumber-play_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26locales%3D*%26secondLocale%3Des&testInfo=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717393976495%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1717326050113/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22second-language-fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1717326050113%22%2C%22timestamp%22%3A1717393976495%7D&brand=phet&ea&fuzz&locales=*&secondLocale=es
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["number-play","second-language-fuzz","unbuilt","query-parameters"]

id: "Sparky Node Puppeteer"
Snapshot from 6/2/2024, 5:00:50 AM
```

**Comment by marlitas** [comment]
Oh boy. There is much work that needs to be done on Make a Ten, but we are not there right now. Unassigning.
