### ISSUE TITLE
CT item not found in Array

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#38]
```
number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1628502226011%22%2C%22timestamp%22%3A1628510484969%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/createObservableArray.js:346:33)
at OnesPlayArea.removePaperNumber (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/model/CountingCommonModel.js:89:23)
at OnesPlayArea.collapseNumberModels (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/model/CountingCommonModel.js:67:10)
at OnesPlayAreaNode.tryToCombineNumbers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/js/common/view/OnesPlayAreaNode.js:275:23)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/view/PaperNumberNode.js:98:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/scenery/js/listeners/PressListener.js:680:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/Action.js:227:18)
id: Bayes Chrome
Snapshot from 8/9/2021, 3:43:46 AM

----------------------------------

number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1628502226011%22%2C%22timestamp%22%3A1628518663940%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/createObservableArray.js:346:33)
at OnesPlayArea.removePaperNumber (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/model/CountingCommonModel.js:89:23)
at OnesPlayArea.collapseNumberModels (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/model/CountingCommonModel.js:67:10)
at OnesPlayAreaNode.tryToCombineNumbers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/js/common/view/OnesPlayAreaNode.js:275:23)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/view/PaperNumberNode.js:98:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/scenery/js/listeners/PressListener.js:680:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/Action.js:227:18)
id: Bayes Chrome
Snapshot from 8/9/2021, 3:43:46 AM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1628502226011%22%2C%22timestamp%22%3A1628510403883%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: value failed isValidValue: -1
Error: Assertion failed: value failed isValidValue: -1
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/ValidatorDef.js:324:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/validate.js:36:18)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/NumberProperty.js:105:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/NumberProperty.js:138:12
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/TinyEmitter.js:86:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/Property.js:271:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/Property.js:186:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/Property.js:341:32)
at OnesPlayAreaNode.onNumberDragFinished (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/js/common/view/OnesPlayAreaNode.js:376:51)
id: Bayes Chrome
Snapshot from 8/9/2021, 3:43:46 AM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1628502226011%22%2C%22timestamp%22%3A1628519646317%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/createObservableArray.js:346:33)
at OnesPlayArea.removePaperNumber (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/model/CountingCommonModel.js:89:23)
at OnesPlayArea.collapseNumberModels (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/model/CountingCommonModel.js:67:10)
at OnesPlayAreaNode.tryToCombineNumbers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/js/common/view/OnesPlayAreaNode.js:275:23)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/view/PaperNumberNode.js:98:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/scenery/js/listeners/PressListener.js:680:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/Action.js:227:18)
id: Bayes Chrome
Snapshot from 8/9/2021, 3:43:46 AM

----------------------------------

number-play : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1628502226011%22%2C%22timestamp%22%3A1628514003121%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/createObservableArray.js:346:33)
at OnesPlayArea.removePaperNumber (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/model/CountingCommonModel.js:89:23)
at OnesPlayArea.collapseNumberModels (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/model/CountingCommonModel.js:67:10)
at OnesPlayAreaNode.tryToCombineNumbers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/js/common/view/OnesPlayAreaNode.js:275:23)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/counting-common/js/common/view/PaperNumberNode.js:98:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/scenery/js/listeners/PressListener.js:680:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/Action.js:227:18)
id: Bayes Chrome
Snapshot from 8/9/2021, 3:43:46 AM

----------------------------------

number-play : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1628502226011%22%2C%22timestamp%22%3A1628521202670%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: -3
Error: Assertion failed: value failed isValidValue: -3
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/ValidatorDef.js:324:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/validate.js:36:18)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/NumberProperty.js:105:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/NumberProperty.js:138:12
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/TinyEmitter.js:86:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/Property.js:271:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/Property.js:186:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/axon/js/Property.js:341:32)
at OnesPlayAreaNode.onNumberDragFinished (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628502226011/number-play/js/common/view/OnesPlayAreaNode.js:376:51)
id: Bayes Chrome
Snapshot from 8/9/2021, 3:43:46 AM
```

**Comment by chrisklus** [comment]
I weirdly cannot reproduce any of these locally, even though they are still happening on CT. I've tried many combinations of fuzz tests shown above. I'm going to work on other known bugs and see if that helps find or improve anything.

**Comment by chrisklus** [comment]
I believe this was related to the Lab Screen that has now been removed, see https://github.com/phetsims/number-play/issues/48#issuecomment-920618588.
