### ISSUE TITLE
CT Cannot read property press of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#48]
```
number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629727363977%22%2C%22timestamp%22%3A1629729683808%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'press' of null
TypeError: Cannot read property 'press' of null
at PaperNumberNode.startDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/counting-common/js/common/view/PaperNumberNode.js:235:28)
at ClosestDragListener.down (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/sun/js/ClosestDragListener.js:92:23)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1885:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1924:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1838:10)
at Input.downEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1652:10)
at Input.touchStartAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:403:12)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/axon/js/Action.js:227:18)
at Input.touchStart (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1212:27)
at InputFuzzer.touchStart (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/InputFuzzer.js:205:25)
id: Bayes Chrome
Snapshot from 8/23/2021, 8:02:43 AM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629727363977%22%2C%22timestamp%22%3A1629730644427%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read property 'press' of null
TypeError: Cannot read property 'press' of null
at PaperNumberNode.startDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/counting-common/js/common/view/PaperNumberNode.js:235:28)
at ClosestDragListener.down (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/sun/js/ClosestDragListener.js:92:23)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1885:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1924:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1838:10)
at Input.downEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1652:10)
at Input.touchStartAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:403:12)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/axon/js/Action.js:227:18)
at Input.touchStart (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1212:27)
at InputFuzzer.touchStart (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/InputFuzzer.js:205:25)
id: Bayes Chrome
Snapshot from 8/23/2021, 8:02:43 AM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629727363977%22%2C%22timestamp%22%3A1629728876979%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read property 'press' of null
TypeError: Cannot read property 'press' of null
at PaperNumberNode.startDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/counting-common/js/common/view/PaperNumberNode.js:235:28)
at ClosestDragListener.down (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/sun/js/ClosestDragListener.js:92:23)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1885:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1924:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1838:10)
at Input.downEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1652:10)
at Input.touchStartAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:403:12)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/axon/js/Action.js:227:18)
at Input.touchStart (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/Input.js:1212:27)
at InputFuzzer.touchStart (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629727363977/scenery/js/input/InputFuzzer.js:205:25)
id: Bayes Chrome
Snapshot from 8/23/2021, 8:02:43 AM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe!

There were a number of bugs in CT for a while that went away when I removed the Lab screen. I'm not surprised there were so many since it was in an incomplete state. I'm going to close them since CT is clear and I won't be bringing the Lab screen until it's in a more finished state. For any that I close for this reason, I'll reference this comment as an explanation.
