### ISSUE TITLE
CT value failed isValidValue: -4

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#52]
May have occured before
```
number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1630344483726%22%2C%22timestamp%22%3A1630346686666%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: value failed isValidValue: -4
Error: Assertion failed: value failed isValidValue: -4
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/axon/js/ValidatorDef.js:324:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/axon/js/validate.js:36:18)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/axon/js/NumberProperty.js:105:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/axon/js/NumberProperty.js:138:12
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/axon/js/TinyEmitter.js:86:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/axon/js/Property.js:271:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/axon/js/Property.js:186:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/axon/js/Property.js:341:32)
at OnesPlayAreaNode.onNumberDragFinished (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630344483726/number-play/js/common/view/OnesPlayAreaNode.js:364:51)
id: Bayes Chrome
Snapshot from 8/30/2021, 11:28:03 AM
```

**Comment by chrisklus** [comment]
This was related to the Lab Screen that has now been removed, see https://github.com/phetsims/number-play/issues/48#issuecomment-920618588.
