### ISSUE TITLE
CT Required is not defined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#58]
```
number-play : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631315771477%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught ReferenceError: required is not defined
ReferenceError: required is not defined
at new pT (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631315771477%7D&fuzz&memoryLimit=1000:864:1667137)
at new WP (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631315771477%7D&fuzz&memoryLimit=1000:864:1806259)
at jP.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631315771477%7D&fuzz&memoryLimit=1000:864:1809458)
at jP.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631315771477%7D&fuzz&memoryLimit=1000:864:848712)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631315771477%7D&fuzz&memoryLimit=1000:864:1133752)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631315771477%7D&fuzz&memoryLimit=1000:864:1133905
id: Bayes Chrome
Snapshot from 9/10/2021, 4:34:37 PM

----------------------------------

number-play : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631314259087%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught ReferenceError: required is not defined
ReferenceError: required is not defined
at new NumeralAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/common/view/NumeralAccordionBox.js:38:13)
at new NumberPlayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/common/view/NumberPlayScreenView.js:94:33)
at TenScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/ten/TenScreen.js:78:16)
at TenScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Sim.js:947:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 9/10/2021, 4:34:37 PM

----------------------------------

number-play : lint
Lint failed with status code 6:
Running "lint" task

/data/share/phet/continuous-testing/ct-snapshots/1631313277318/number-play/js/common/view/NumeralAccordionBox.js
38:13 error 'required' is not defined no-undef
40:21 error 'required' is not defined no-undef
41:22 error 'required' is not defined no-undef
42:18 error 'required' is not defined no-undef

✖ 4 problems (4 errors, 0 warnings)

Warning: 4 errors and 0 warnings Use --force to continue.

Aborted due to warnings.
Snapshot from 9/10/2021, 4:34:37 PM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631314151310%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught ReferenceError: required is not defined
ReferenceError: required is not defined
at new NumeralAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/common/view/NumeralAccordionBox.js:38:13)
at new NumberPlayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/common/view/NumberPlayScreenView.js:94:33)
at TenScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/ten/TenScreen.js:78:16)
at TenScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Sim.js:947:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 9/10/2021, 4:34:37 PM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631314600589%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught ReferenceError: required is not defined
ReferenceError: required is not defined
at new NumeralAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/common/view/NumeralAccordionBox.js:38:13)
at new NumberPlayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/common/view/NumberPlayScreenView.js:94:33)
at TenScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/ten/TenScreen.js:78:16)
at TenScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Sim.js:947:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 9/10/2021, 4:34:37 PM

----------------------------------

number-play : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1631313277318%22%2C%22timestamp%22%3A1631314616315%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught ReferenceError: required is not defined
ReferenceError: required is not defined
at new NumeralAccordionBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/common/view/NumeralAccordionBox.js:38:13)
at new NumberPlayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/common/view/NumberPlayScreenView.js:94:33)
at TenScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/number-play/js/ten/TenScreen.js:78:16)
at TenScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Sim.js:947:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631313277318/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 9/10/2021, 4:34:37 PM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! This doesn't appear to have been a problem since 9/10, so I'm going to close.
