### ISSUE TITLE
CT: Module not found

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#59]
In https://github.com/phetsims/number-play/issues/30, I started making a new file by using a file from make-a-ten as a template, and some of the imports that were reused did not get updated to the correct path. For some reason, they were still working on my local copy so I never saw any issues until CT and phettest started having problems (notified by @KatieWoe).

```
number-play : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (number-play, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../../counting-common/js/common/view/CountingCreatorNode.js' in '/data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/js/common/view'
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/Compilation.js:1773:28
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:814:13
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:286:22
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:442:22
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:676:25
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:885:8
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:1005:5
Full Error details:
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../../counting-common/js/common/view/CountingCreatorNode.js' in '/data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/js/common/view'

Webpack build errors: [
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../../counting-common/js/common/view/CountingCreatorNode.js' in '/data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/js/common/view'
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/Compilation.js:1773:28
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:814:13
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:286:22
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:442:22
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:676:25
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:885:8
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:1005:5
resolve '../../../../../counting-common/js/common/view/CountingCreatorNode.js' in '/data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/js/common/view'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/package.json (relative path: ./js/common/view)
Field 'browser' doesn't contain a valid alias configuration
No description file found in /data/share/phet/continuous-testing/ct-snapshots/counting-common/js/common/view or above
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/counting-common/js/common/view/CountingCreatorNode.js doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/counting-common/js/common/view/CountingCreatorNode.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/counting-common/js/common/view/CountingCreatorNode.js.json doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/counting-common/js/common/view/CountingCreatorNode.js.wasm doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/counting-common/js/common/view/CountingCreatorNode.js doesn't exist,
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../../phet-core/js/merge.js' in '/data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/js/common/view'
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/Compilation.js:1773:28
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:814:13
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:286:22
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:442:22
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:676:25
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:885:8
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:1005:5
resolve '../../../../../phet-core/js/merge.js' in '/data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/js/common/view'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/package.json (relative path: ./js/common/view)
Field 'browser' doesn't contain a valid alias configuration
No description file found in /data/share/phet/continuous-testing/ct-snapshots/phet-core/js or above
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/phet-core/js/merge.js doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/phet-core/js/merge.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/phet-core/js/merge.js.json doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/phet-core/js/merge.js.wasm doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/phet-core/js/merge.js doesn't exist,
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../../scenery/js/nodes/HBox.js' in '/data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/js/common/view'
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/Compilation.js:1773:28
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:814:13
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:286:22
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:442:22
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:676:25
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:885:8
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:1005:5
resolve '../../../../../scenery/js/nodes/HBox.js' in '/data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/js/common/view'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/package.json (relative path: ./js/common/view)
Field 'browser' doesn't contain a valid alias configuration
No description file found in /data/share/phet/continuous-testing/ct-snapshots/scenery/js/nodes or above
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/scenery/js/nodes/HBox.js doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/scenery/js/nodes/HBox.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/scenery/js/nodes/HBox.js.json doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/scenery/js/nodes/HBox.js.wasm doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/scenery/js/nodes/HBox.js doesn't exist,
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../../sun/js/Panel.js' in '/data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/js/common/view'
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/Compilation.js:1773:28
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:814:13
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:286:22
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:442:22
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:676:25
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:885:8
at /data/share/phet/continuous-testing/ct-snapshots/1631811802011/chipper/node_modules/webpack/lib/NormalModuleFactory.js:1005:5
resolve '../../../../../sun/js/Panel.js' in '/data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/js/common/view'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1631811802011/number-play/package.json (relative path: ./js/common/view)
Field 'browser' doesn't contain a valid alias configuration
No description file found in /data/share/phet/continuous-testing/ct-snapshots/sun/js or above
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/sun/js/Panel.js doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/sun/js/Panel.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/sun/js/Panel.js.json doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/sun/js/Panel.js.wasm doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/sun/js/Panel.js doesn't exist
]
Snapshot from 9/16/2021, 11:03:22 AM
```

**Comment by chrisklus** [comment]
Fixed above, closing.
