### ISSUE TITLE
CT setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#9]
```
number-play : fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/number-play/number-play_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/assert/js/assert.js:22:13)
    at VBox.setCenterY (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:2725:15)
    at VBox.set centerY [as centerY] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:2731:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:5145:23
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/sherpa/lib/lodash-4.17.4.js:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/sherpa/lib/lodash-4.17.4.js:9359:14)
    at VBox.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:5132:7)
    at VBox.LayoutBox [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/LayoutBox.js:104:8)
    at new VBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/VBox.js:30:13)
    at new ShapeGroupNode (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/fractions-common/js/building/view/ShapeGroupNode.js:134:27)
id: Bayes Chrome
Approximately 4/12/2020, 7:49:56 PM
number-play : fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/number-play/number-play_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/assert/js/assert.js:22:13)
    at VBox.setCenterY (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:2725:15)
    at VBox.set centerY [as centerY] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:2731:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:5145:23
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/sherpa/lib/lodash-4.17.4.js:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/sherpa/lib/lodash-4.17.4.js:9359:14)
    at VBox.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:5132:7)
    at VBox.LayoutBox [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/LayoutBox.js:104:8)
    at new VBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/VBox.js:30:13)
    at new ShapeGroupNode (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/fractions-common/js/building/view/ShapeGroupNode.js:134:27)
id: Bayes Chrome
Approximately 4/12/2020, 7:49:56 PM
number-play : xss-fuzz : load
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/number-play/number-play_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/assert/js/assert.js:22:13)
    at VBox.setCenterY (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:2725:15)
    at VBox.set centerY [as centerY] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:2731:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:5145:23
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/sherpa/lib/lodash-4.17.4.js:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/sherpa/lib/lodash-4.17.4.js:9359:14)
    at VBox.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:5132:7)
    at VBox.LayoutBox [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/LayoutBox.js:104:8)
    at new VBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/VBox.js:30:13)
    at new ShapeGroupNode (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/fractions-common/js/building/view/ShapeGroupNode.js:134:27)
id: Bayes Chrome
Approximately 4/12/2020, 7:49:56 PM
number-play : xss-fuzz : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/number-play/number-play_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/assert/js/assert.js:22:13)
    at VBox.setCenterY (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:2725:15)
    at VBox.set centerY [as centerY] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:2731:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:5145:23
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/sherpa/lib/lodash-4.17.4.js:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/sherpa/lib/lodash-4.17.4.js:9359:14)
    at VBox.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/Node.js:5132:7)
    at VBox.LayoutBox [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/LayoutBox.js:104:8)
    at new VBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/scenery/js/nodes/VBox.js:30:13)
    at new ShapeGroupNode (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/fractions-common/js/building/view/ShapeGroupNode.js:134:27)
id: Bayes Chrome
Approximately 4/12/2020, 7:49:56 PM
```

**Comment by chrisklus** [comment]
This issue is very old and based on the error, is not something that I think would happen infrequently or be hard to come across if was still a problem, so I'm going to close.
